spring.datasource.url=jdbc:h2:mem:locadora;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2

app.security.mode=INSECURE
app.security.encryption-key=ChangeMe-32chars-key-1234567890

# Para ativar o laboratório vulnerável, substitua por INSECURE
# app.security.mode=INSECURE
